// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ebR1p3EaaF503rSUZOMXpWCXqlIILpc',
    appId: '1:678365661675:web:2399f339a601b4bfa831ae',
    messagingSenderId: '678365661675',
    projectId: 'yg-a-ff86b',
    authDomain: 'yg-a-ff86b.firebaseapp.com',
    storageBucket: 'yg-a-ff86b.firebasestorage.app',
    measurementId: 'G-DLX5DGTT90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQi5qthfXu6TyOwVJFNM_BrVcDnC8XfWg',
    appId: '1:678365661675:android:2f449c370ae6c3e0a831ae',
    messagingSenderId: '678365661675',
    projectId: 'yg-a-ff86b',
    storageBucket: 'yg-a-ff86b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN0zkFywejykHvFRWCs0Gywj9fkr84W3s',
    appId: '1:678365661675:ios:f8abab156d65c410a831ae',
    messagingSenderId: '678365661675',
    projectId: 'yg-a-ff86b',
    storageBucket: 'yg-a-ff86b.firebasestorage.app',
    iosBundleId: 'com.example.ygAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN0zkFywejykHvFRWCs0Gywj9fkr84W3s',
    appId: '1:678365661675:ios:f8abab156d65c410a831ae',
    messagingSenderId: '678365661675',
    projectId: 'yg-a-ff86b',
    storageBucket: 'yg-a-ff86b.firebasestorage.app',
    iosBundleId: 'com.example.ygAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8ebR1p3EaaF503rSUZOMXpWCXqlIILpc',
    appId: '1:678365661675:web:e216d17052ee70dca831ae',
    messagingSenderId: '678365661675',
    projectId: 'yg-a-ff86b',
    authDomain: 'yg-a-ff86b.firebaseapp.com',
    storageBucket: 'yg-a-ff86b.firebasestorage.app',
    measurementId: 'G-6W11RB1025',
  );

}